version: '3.8'


services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
      - ./init/google:${DATA_PATH}:ro
    environment:
      # bot token
      - TOKEN=${TOKEN}
      # db connection
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      # google calendar
      - CALENDAR_ID=${CALENDAR_ID}
      - CALENDAR_JSON_PATH=${DATA_PATH}/${CALENDAR_JSON_PATH}
      - TZ=Asia/Tokyo
    tty: true
    depends_on:
      - db
    command: ["python3", "main.py"]
    restart: always

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d
    # ports:
    #   - ${LOCAL_DB_PORT}:${PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Tokyo
    restart: always