version: '3.8'

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
      - ./init/google:${DATA_PATH}:ro
    environment:
      # bot token
      - TOKEN=${TOKEN}
      # google calendar
      - CALENDAR_ID=${CALENDAR_ID}
      - CALENDAR_JSON_PATH=${DATA_PATH}/${CALENDAR_JSON_PATH}
      # TimeZone
      - TZ=Asia/Tokyo
    env_file:
      - db.env
    tty: true
    depends_on:
      - db
    command: ["python3", "main.py"]
    restart: always

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d
    ports:
      - ${LOCAL_DB_PORT}:${PORT}
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - db.env
    restart: always
    
  redis:
    image: redis:alpine
    volumes:
      - "./redis:/data"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 20M

  rediscommander:
    image: rediscommander/redis-commander:latest
    ports:
      - 18081:8081
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
