version: "3.8"

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
      - ./init/google:${DATA_PATH}:ro
    environment:
      # bot token
      - TOKEN=${TOKEN}
      # google calendar
      - CALENDAR_ID=${CALENDAR_ID}
      - CALENDAR_JSON_PATH=${DATA_PATH}/${CALENDAR_JSON_PATH}
      # TimeZone
      - TZ=Asia/Tokyo
    env_file:
      - db.env
    tty: true
    depends_on:
      - db
    command: ["python3", "main.py"]
    restart: always
    networks:
      - default

  db:
    image: postgres:15.2-alpine3.17
    hostname: ${DBHOSTNAME}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - db.env
    restart: always
    networks:
      - default
      - genshin_network

  redis:
    image: redis:alpine
    volumes:
      - "./redis:/data"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 20M
    networks:
      - default

  redis-commander:
    hostname: redis-commander
    container_name: redis-commander
    image: rediscommander/redis-commander
    networks:
      - default
      - genshin_network
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=80

networks:
  default:
  genshin_network:
    external:
      name: ${GENSHINDB}
